### PR TITLE
Add Font Awesome Link

### PR DESCRIPTION
**Pull request by vermilion4**
## What does this pull request do?
Add Fontawesome CDN link to head to allow font awesome icons to show.

## What is the relevant issue link: 
[Issue Link](https://github.com/CommunityPro/portfolio-html/issues/68)

### CODE REVIEW

**Comment by Evavic44** [comment]
You even added the icon. Nice. 🙌🏾

We will need to raise an issue to rotate the icon 30deg to match the design.

**Comment by vermilion4** [comment]
> You even added the icon. Nice. 🙌🏾
> 
> We will need to raise an issue to rotate the icon 30deg to match the design. 

Oh no...the icon was already there. Yeah we'll need to do that

**Comment by Evavic44** [comment]
You can raise the issue if you and I'll check it out later. Goodnight. 🙏🏽

**Comment by vermilion4** [comment]
alright, I have done that... Have a good night.

**Pull request merged**
