### PR TITLE
Fix toogle issue

### LINKED ISSUE #106: [FEAT] - Swap lightmode icons.
## Is your feature request related to a problem? Please describe.

Light and dark mode icons inverted. 

## Describe the solution you'd lIke. 

Swap the light mode icon to show on dark mode and dark mode icon to show on light mode.

### PR DESCRIPTION
**Pull request by Evavic44**
## What does this pull request do?
Fix lightmode and darkmode toggle issue

## What is the relevant issue link: 
closes #106

### CODE REVIEW

**Comment by vermilion4** [comment]
Perfect @Evavic44

**Comment by vermilion4** [comment]
Also this is for people that use their browsers darkmode normally like me, would it be possible to add a display:none for one or the other? Like when the dark icon is there the light icon should be hidden, or something like that. Because for me this is what it looks like

**Comment by vermilion4** [comment]
> Also this is for people that use their browsers darkmode normally like me, would it be possible to add a display:none for one or the other? Like when the dark icon is there the light icon should be hidden, or something like that. Because for me this is what it looks like
> 

This is for mobile sha as it normally wouldn't affect web all the same

**Comment by Evavic44** [comment]
> Also this is for people that use their browsers darkmode normally like me, would it be possible to add a display:none for one or the other? Like when the dark icon is there the light icon should be hidden, or something like that. Because for me this is what it looks like 

Yeah, tried to do that with CSS but it didn't work, might have to opt for a JS solution. In the meantime, I'm closing this, since the primary issue has been fixed. We can raise a new issue to address the display of the icons. 🙌🏾

**Pull request merged**
