### PR TITLE
Fixed spacing of elements

### PR DESCRIPTION
**Pull request by manishbajagai2**
## What does this pull request do?
Fixes spacing of elements

## What is the relevant issue link: 
[relevant issue link](https://github.com/CommunityPro/portfolio-html/issues/63)

## Screenshot
image

### CODE REVIEW

**Comment by Evavic44** [comment]
Thanks, @manishbajagai2 for the PR. Can you pull the latest changes and push again? You have some merge conflicts that need fixing.

**Comment by manishbajagai2** [comment]
i don't have write access to this repository. Therefore the conflict states that only with write access can merge the conflicting files

**Comment by manishbajagai2** [comment]
@Evavic44 Check out the below image and see if you can approve the files changed :
image

**Comment by Evavic44** [comment]
> Thanks, @manishbajagai2 for the PR. Can you pull the latest changes and push again? You have some merge conflicts that need fixing.

You have to do it with your text editor. I can't even fix the conflicts myself.

**Comment by Evavic44** [comment]
Do a 

```bash
git fetch upstream
git merge upstream/main
```

You should see the conflicts, see if you can fix them. 
If you can't then close this PR and make another PR with a different branch.

**Comment by vermilion4** [comment]
True you have to do it via your terminal. The problem is you didn't pull before pushing,  so your folder is still called template rather than docs @manishbajagai2

**Comment by Evavic44** [comment]
Closing this PR due to inactivity. You can raise another if you still want to fix this issue, until then it will be available for anyone.

**Pull request closed without merging**
