### PR TITLE
Externally linked the Contributing guidelines to the README

### PR DESCRIPTION
**Pull request by frankiefab100**
This fixes issue #14

### CODE REVIEW

**Review by Evavic44 — CHANGES_REQUESTED** [review]
Can you use the URL link, instead of the folder tree?
Here's the link
https://github.com/CommunityPro/portfolio-html/blob/main/CONTRIBUTING.md

**Comment by frankiefab100** [comment]
Alright

**Review by Evavic44 — APPROVED** [review]
Awesome work @frankiefab100

**Comment by Evavic44** [comment]
We have other empty links on the README, you fix them as well @frankiefab100

**Comment by frankiefab100** [comment]
I would like others to try, i can guide them.

**Comment by Evavic44** [comment]
> I would like others to try, i can guide them.

That is very thoughtful. Thanks @frankiefab100 
If you raise the issue, you can share them in the group link so they see it. 🙏🏽✨

**Comment by frankiefab100** [comment]
sure, I will do so.

**Pull request merged**
